name: vercheck
version: 0.0.1
description: A minimal web server using the shelf package.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http: ">=0.11.1+3 <0.12.0"
  args: '>=0.10.0 <0.13.0'
  pub_semver: ">=1.1.0 <2.0.0"
  start: ">=0.2.7 <0.3.0"
  postgresql: ">=0.3.0+2 <0.4.0"
  yaml: ">=2.1.2 <3.0.0"
  redis_client: ">=0.1.15 <0.2.0"
  oauth2: ">=0.9.3 <0.10.0"
  dbmapper:
    git: git://github.com/Adracus/dbmapper.git
dev_dependencies:
  unittest: any